steps:
  # Step 1: Build the Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ems-frontend'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # Step 2: Push the Image to the Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ems-frontend']

  # Step 3: Deploy automatically to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ems-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ems-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--update-secrets'
      - 'SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_PUBLISHABLE_KEY=SUPABASE_PUBLISHABLE_KEY:latest'

images:
  - 'gcr.io/$PROJECT_ID/ems-frontend'
